# Lista de ejercicios 2
***

* Explica las siguientes expresiones:

In [13]:
# Declaramos una vector x
x<- c(1,2,3,4)
sum(!is.na(x)) # Primero is.na evalúa cada elemento de x, si es de tipo NA será 1, sino 0, pero como está 
               # la negación, entonces retornará 1 por cada valor de x, así la suma de todos esos valores será 3

c(x,x[-(1:length(x))]) # En este caso se concatena dos vectores, el vector x con el mismo vector x pero este último 
                    # no tiene valores, ya que al aplicarle el -(1:length(x)) no se muestra ningún valor de x. Entonces
                    # si concatenamos x con x[vacio] será el mismo vector x 

x[length(x) + 1] / length(x) # length( x) + 1 es una valor NA, por lo tengo al dividir el valor NA evaluado en el
                             # vector x, entre length(x) nos dará NA. 

sum(x > mean(x)) # Nos sumará todos los valores que cumplen la condicional. Si cumple será 1 sino 0. 

[1] 4

[1] 1 2 3 4

[1] NA

[1] 2

* Pregunta 2:

In [14]:
# Declaramos la función sinh
sinh <- function(x) {
   
  p <- exp(x) - exp(-x) / 2
  print(p) #mostramos p
  
}

* Pregunta 3:

In [15]:
# Generamos una secuencia con la función seq que varía en 0.1 
x <- seq( from = 3, to = 6, by = 0.1)
y <- exp(x)* cos(x)
y

[1] -19.884531 -22.178753 -24.490697 -26.773182 -28.969238 -31.011186
 [7] -32.819775 -34.303360 -35.357194 -35.862834 -35.687732 -34.685042
[13] -32.693695 -29.538816 -25.032529 -18.975233 -11.157417  -1.362099
[19]  10.632038  25.046705  42.099201  61.996630  84.929067 111.061586
[25] 140.525075 173.405776 209.733494 249.468441 292.486707 338.564378
[31] 387.360340

* Pregunta 4:

In [16]:
#Usamos la función paste para poder concatenar vectores que luego los convertiŕa a caracter
# La función rep se encarga de poder repetir la palabra "vector"
paste(rep("vector") , c(1:30))

#Usamos sep = "", para poder juntar los términos
paste(rep("fn") , c(1:30), sep = "")

[1] "vector 1"  "vector 2"  "vector 3"  "vector 4"  "vector 5"  "vector 6" 
 [7] "vector 7"  "vector 8"  "vector 9"  "vector 10" "vector 11" "vector 12"
[13] "vector 13" "vector 14" "vector 15" "vector 16" "vector 17" "vector 18"
[19] "vector 19" "vector 20" "vector 21" "vector 22" "vector 23" "vector 24"
[25] "vector 25" "vector 26" "vector 27" "vector 28" "vector 29" "vector 30"

[1] "fn1"  "fn2"  "fn3"  "fn4"  "fn5"  "fn6"  "fn7"  "fn8"  "fn9"  "fn10"
[11] "fn11" "fn12" "fn13" "fn14" "fn15" "fn16" "fn17" "fn18" "fn19" "fn20"
[21] "fn21" "fn22" "fn23" "fn24" "fn25" "fn26" "fn27" "fn28" "fn29" "fn30"

* Pregunta 5:

In [17]:
DF <- D(expression(cos(x)/sin(x)), "x") # DF retorna la derivada de  "expression", la cual es -csc(x)^2 
  x <- pi/4  # Después le damos a x el valor de pi/4
  eval(DF)  # Por último evaluamos ese valor de x en DF. 

[1] -2

* Pregunta 6:

* Pregunta 7:

In [18]:
#Primera secuencia 
z <-rep( seq(0:4), each = 5)
z

#Segunda secuencia 
rep(0:4,5)

[1] 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5

[1] 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4

* Pregunta 8:

In [24]:
x <- 2:38 # Vector de 2 a 38
x <- x[x%%2==0] #Solo coge los índices pares

fraccion1 <- x/(x+1) 
fraccion2 <- cumprod(fraccion1) # aplicamos la fución cumprod ya que acumula los productos 
suma <- 1+sum(fraccion2)
sprintf("La suma es %f",suma)
 

[1] "La suma es 6.976346"

* Pregunta 9:

In [25]:
# Utilizamos la funcion expand.grid para poder obtener todos los valores posibles que se pueden dar en los
# experimentos 
Tabla <- expand.grid(Moneda = sample(c("C","S"), replace = T), Dados = sample(c(1:6),replace = T))
Tabla
  

Moneda Dados
1  C      5    
2  S      5    
3  C      3    
4  S      3    
5  C      3    
6  S      3    
7  C      1    
8  S      1    
9  C      1    
10 S      1    
11 C      4    
12 S      4

* Pregunta 10:

In [27]:
#Creamos un vector con los colores pedidos.
d <- c("rojo","azul","verde","blanco","negro","amarillo")
combn(d,3) #usamos esta funcion para visualizar las combinaciones posibles sin repetición
choose(6,3) # Mostramos el numero de combinaciones 

[,1]  [,2]   [,3]  [,4]     [,5]   [,6]  [,7]     [,8]   [,9]     [,10]   
[1,] rojo  rojo   rojo  rojo     rojo   rojo  rojo     rojo   rojo     rojo    
[2,] azul  azul   azul  azul     verde  verde verde    blanco blanco   negro   
[3,] verde blanco negro amarillo blanco negro amarillo negro  amarillo amarillo
     [,11]  [,12] [,13]    [,14]  [,15]    [,16]    [,17]  [,18]    [,19]   
[1,] azul   azul  azul     azul   azul     azul     verde  verde    verde   
[2,] verde  verde verde    blanco blanco   negro    blanco blanco   negro   
[3,] blanco negro amarillo negro  amarillo amarillo negro  amarillo amarillo
     [,20]   
[1,] blanco  
[2,] negro   
[3,] amarillo

[1] 20

* Pregunta 11:

In [28]:
# Tenemos el mismo conjunto de colores 
d <- c("rojo","azul","verde","blanco","negro","amarillo")
combn(d,1) #Eligiendo un color
combn(d,2) #Eligiendo dos colores
combn(d,3) #Eligiendo tres colores 


[,1] [,2] [,3]  [,4]   [,5]  [,6]    
[1,] rojo azul verde blanco negro amarillo

[,1] [,2]  [,3]   [,4]  [,5]     [,6]  [,7]   [,8]  [,9]     [,10]  [,11]
[1,] rojo rojo  rojo   rojo  rojo     azul  azul   azul  azul     verde  verde
[2,] azul verde blanco negro amarillo verde blanco negro amarillo blanco negro
     [,12]    [,13]  [,14]    [,15]   
[1,] verde    blanco blanco   negro   
[2,] amarillo negro  amarillo amarillo

[,1]  [,2]   [,3]  [,4]     [,5]   [,6]  [,7]     [,8]   [,9]     [,10]   
[1,] rojo  rojo   rojo  rojo     rojo   rojo  rojo     rojo   rojo     rojo    
[2,] azul  azul   azul  azul     verde  verde verde    blanco blanco   negro   
[3,] verde blanco negro amarillo blanco negro amarillo negro  amarillo amarillo
     [,11]  [,12] [,13]    [,14]  [,15]    [,16]    [,17]  [,18]    [,19]   
[1,] azul   azul  azul     azul   azul     azul     verde  verde    verde   
[2,] verde  verde verde    blanco blanco   negro    blanco blanco   negro   
[3,] blanco negro amarillo negro  amarillo amarillo negro  amarillo amarillo
     [,20]   
[1,] blanco  
[2,] negro   
[3,] amarillo

* Pregunta 12:

In [32]:
# Parte a) 
 #Primera forma 
 x<- c(0:12) #Valores que toma x
  #funcion que evalua cada valor de x mostrando su distribución binomial
  bin <- function(x){
    co <- choose(12,x) #coeficiente binomial
    p <- (1/3)^x
    q <- (2/3)^(12-x)
    resul <- co*p*q
    resul
  }
 
  bin(x)

  #Segunda forma 
   #Utilizando la funcion dbinom
  p <-dbinom(x, 12, 1/3)
  p

[1] 7.707347e-03 4.624408e-02 1.271712e-01 2.119520e-01 2.384460e-01
 [6] 1.907568e-01 1.112748e-01 4.768921e-02 1.490288e-02 3.311751e-03
[11] 4.967626e-04 4.516023e-05 1.881676e-06

[1] 7.707347e-03 4.624408e-02 1.271712e-01 2.119520e-01 2.384460e-01
 [6] 1.907568e-01 1.112748e-01 4.768921e-02 1.490288e-02 3.311751e-03
[11] 4.967626e-04 4.516023e-05 1.881676e-06

In [33]:
# Parte b)  Calculando el CDF de X
 # Primera forma
  cdf <-cumsum(bin(x))
  cdf
 
 #Segunda forma 
  pbinom(x,12,1/3)

[1] 0.007707347 0.053951426 0.181122646 0.393074678 0.631520714 0.822277544
 [7] 0.933552360 0.981241568 0.996144445 0.999456196 0.999952958 0.999998118
[13] 1.000000000

[1] 0.007707347 0.053951426 0.181122646 0.393074678 0.631520714 0.822277544
 [7] 0.933552360 0.981241568 0.996144445 0.999456196 0.999952958 0.999998118
[13] 1.000000000

* Pregunta 13:

* Pregunta 14:

* Pregunta 15:

In [44]:
# Se usa set.seed() para que sea nuestra semilla, es decir, que cada vez que se ejecute saldrá el mismo resultado 
set.seed(50)
 xVec <- sample(0:999,250, replace = T)
 yVec <- sample(0:999,250, replace = T)