# Solución de ejercicios - Tarea 5

1) Definimos:

```R
 > x <- c(5,2,1,4) ; y <- rep(1,5)
```

   Predice las soluciones antes de escribir los comandos

(a) 
 ```R 
  > sum(x) = 12
  > range(x) = 1 5 
  > sum(y) = 5
  > length(y) = 5
 ```
(b) 
 ```R
  > c(x,y,13) = 5 2 1 4 1 1 1 1 1 13  #concatena los vectores
 ```
(c)
```R
  > x[4] * y[2] = (4)*1 = 4
  > x[2:4] + x[1:3] = 2 1 4 + 5 2 1 = 7 3 5 
```
(d)
 ```R
  > x <= 2 # nos devuelve un valor logico, True o False, dependiendo de que valores cumplen
           # con la condicion 
           # FALSE TRUE TRUE FALSE 
  > x[x<=2] #Devolverá los valores que cumplen la condicion -->  2 1 
  > x[(x != 5) & (x>3)]  = 4 
 ```
(e)
 ```R
  > rep(1:4,2) = 1 2 3 4 1 2 3 4 
  > rep(1:4, each = 2) = 1 1 2 2 3 3 4 4
  >rep(1:4,c(2,1,2,1)) = 1 1 2 3 3 4
  > rep(1:4, each = 2, len = 10) = 1 1 2 2 3 3 4 4 1 1 # realiza el reciclado
 ```
(f)
 ```R
  > 2:3^2 = 2 3 4 5 6 7 8 9
  > seq(from = 2, to = -3) * c(-1,1) = 2 1 0 -1 -2 -3
 ```

2)  
   * Describe diferencias entre las estructuras fundamentales de **R**: `vectores`, `matrices`, `arrays` y `listas`. Usa ejemplos para demostrar esas diferencias.

a) Vectores:   
   1. Son de una dimensión.
   2. Sus valores son homogéneos, de tipo lógico,numérico o carácter.

In [3]:
 # Ejemplo : 
          x <- c(1,4,5)
          y <- c(2,3,2)
          c(x,y)

[1] 1 4 5 2 3 2

   b) Matrices:  
   1. Son bidimensionales.  
   2. Sus valores se ordenan por filas y columnas.

In [3]:
#Ejemplo

     z <- matrix(c(x,y), nrow = 2, ncol = 3)
     z

[,1] [,2] [,3]
[1,] 1    5    3   
[2,] 4    2    2

c) Arrays:
 1. Son de varias dimensiones

In [4]:
# Ejemplo:

   array(c(x,y), c(2,2,2))
       

, , 1

     [,1] [,2]
[1,]    1    5
[2,]    4    2

, , 2

     [,1] [,2]
[1,]    3    1
[2,]    2    4

d) Listas:
  1. Es una estructura donde podemos unir varios tipos de estructuras
  2. Tiene elementos de diferentes tipos. 

In [69]:
# Ejemplo:Como se puede observar son diferentes tipos de datos, caracter y numérico, en este caso. 
       
   familia <- list(padre = "Javier", madre = "Maria", numero.hijos = 3, nombre.hijos = c("Mathias","Carla","Lorena"),edades.hijos = c(6,12,21),ciudad = "Madrid") 
   familia 
        

$padre
[1] "Javier"

$madre
[1] "Maria"

$numero.hijos
[1] 3

$nombre.hijos
[1] "Mathias" "Carla"   "Lorena" 

$edades.hijos
[1]  6 12 21

$ciudad
[1] "Madrid"

* Explicar las diferencias entre las funciones `rbind()`, `cbind()` y `merge()` para combinar dos estructuras de dos dimensiones en **R**. Usa ejemplos para demostrar esas diferencias.

a) `rbind()`: Combina dos matrices pero los ordena de acuerdo a las filas.

In [7]:
# Ejemplo: 
   x <- matrix( 1:6, nrow = 2 )
   y <- matrix( 4:9, nrow = 2)
   rbind(x,y)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6   
[3,] 4    6    8   
[4,] 5    7    9

b) `cbind()`: Combina dos matrices pero ordenandolos de acuerdo a las columnas.

In [9]:
# Ejemplo: Usamos las mismas matrices, así tenemos: 
  cbind(x,y)       

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    3    5    4    6    8   
[2,] 2    4    6    5    7    9

 Observamos que se añadió toda la matriz "y" como parte de las columnas de "x". 

c) `merge()`: Combina dos dataframe, pero sin necesidad de que las filas no esten en el orden correcto para poder ser usadas. Si tienen algo en común, simplemente los hace coincidir. 

In [10]:
# Ejemplo: 
   A <- data.frame(id = c("A","B","C","D"), edad = c(23,24,26,27)) 
   B <- data.frame(genero= c("M","F","M","F"),id = c("A","B","C","D"))
   merge(A,B)

id edad genero
1 A  23   M     
2 B  24   F     
3 C  26   M     
4 D  27   F

Se observa que como ambos tienen id, no se repite dos veces la columna (id) solo los hace coincidir. 

3) 

a) Construye y almacena una matriz 4x2 que se completa por filas con los valores 4.3,3.1,8.2,3.2,0.9,1.6 y 6.5, en ese orden.

In [10]:
   p<- c(4.3,3.1,8.2,8.2,3.2,0.9,1.6,6.5)
   n <- matrix(p,nrow= 4, ncol= 2, byrow = T )
   n

[,1] [,2]
[1,] 4.3  3.1 
[2,] 8.2  8.2 
[3,] 3.2  0.9 
[4,] 1.6  6.5

b) Confirma que las dimensiones de la matriz de (a) son 3 × 2 si se elimina una fila.

In [9]:
    n <- n[-4,] # se elimina la fila 4 
    n
    dim(n)  # se muestra la dimension de la nueva matriz n 

[,1] [,2]
[1,] 4.3  3.1 
[2,] 8.2  8.2 
[3,] 3.2  0.9

[1] 3 2

c) Sobrescribe la segunda columna de la matriz de (a) con esa misma columna ordenada de menor a mayor.

In [11]:
     n[,2] <- sort(n[,2]) # aplicamos sort para ordenar la columna 2 
     n

[,1] [,2]
[1,] 4.3  0.9 
[2,] 8.2  3.1 
[3,] 3.2  6.5 
[4,] 1.6  8.2

d) ¿Qué devuelve R si se elimina la cuarta fila y la primera columna de (c)?. Utiliza matrix para asegurar que el resultado sea una matriz de una sola columna, en lugar de un vector.

In [5]:
      n <- matrix(n[-4,-1])
      n
      is.matrix(n)

[,1]
[1,] 0.9 
[2,] 3.1 
[3,] 6.5

[1] TRUE

e) Guarde los cuatro elementos inferiores de (c) como una nueva matriz 2 × 2.

In [16]:
  n1 <-matrix(c(n[3,],n[4,]),nrow = 2, byrow = T)
  n1 
  print("Dimensión de n1")
  dim(n1)

[,1] [,2]
[1,] 3.2  6.5 
[2,] 1.6  8.2

[1] "Dimensión de n1"


[1] 2 2

f) ) Sobrescribe en este orden los elementos de (c) en las posiciones (4, 2),(1, 2),(4, 1) y (1, 1) con $\frac{1}{2}$ de los dos valores de la diagonal de (e).

In [17]:
   n[c(4,1),1:2] <- 1/2 * diag(n1)
   n 

[,1] [,2]
[1,] 4.1  4.1 
[2,] 8.2  3.1 
[3,] 3.2  6.5 
[4,] 1.6  1.6

4) Calcula lo siguiente:

<center/>  $\tfrac{2}{7}   \begin{bmatrix}    
                1 & 2\\ 
                2 & 4\\    
                7 & 6
                \end{bmatrix}  -  \begin{bmatrix}    
                                      10 & 20\\ 
                                      30 & 40\\    
                                      50 & 60
                                  \end{bmatrix} $  <center/>

In [19]:
     M1 <- matrix(c(1,2,2,4,7,6), nrow = 3, byrow = T)
     M2 <- matrix(10*seq(1,6),nrow=3,byrow = T)
     print("Matriz M1")
     M1
     print("Matriz M2")
     M2
     produc <- ((2/7) * M1) - M2
     print("Resultado:")
     produc # mostramos el resultado 

[1] "Matriz M1"


[,1] [,2]
[1,] 1    2   
[2,] 2    4   
[3,] 7    6

[1] "Matriz M2"


[,1] [,2]
[1,] 10   20  
[2,] 30   40  
[3,] 50   60

[1] "Resultado:"


[,1]       [,2]     
[1,]  -9.714286 -19.42857
[2,] -29.428571 -38.85714
[3,] -48.000000 -58.28571

5) Almacena estas dos matrices:
 
 <center/> $A =  \begin{bmatrix}
 1\\ 
 2\\ 
 7
 \end{bmatrix} \, \, \, \: \: \: \: \,  \, B = \begin{bmatrix}
                                                  3\\ 
                                                  4\\ 
                                                  8
                                                 \end{bmatrix}  $ <center/>
                                                 
¿ Cuál de las siguientes multiplicaciones son posibles?. Para los que son, calcula el resultado

In [20]:
A <- matrix( c(1,2,7), nrow = 3)
B <- matrix(c(3,4,8), nrow = 3)
print("Matriz A")
A
print("Dimensión de A:")
dim(A)
print("Matriz B")
B
print("Dimensión de B:")
dim(B)

# A x B, no se puede realizar ya que las matrices no son de 3x1 y 1x3. 
# t(A) x B si se puede ya que sus argumentos o dimensiones son compatibles para la multiplicación usual de matrices
t(A) %*% B

# t(B)* (A*t(A)) también se puede realizar la operación
t(B) %*% (A%*%t(A))

# ((B*t(B)) + (A*t(A) - 100*I3)) ^ -1, tambien se puede realizar ya que sus indices son compatibles. 
I3 <- diag(1, nrow = 3) #matriz identidad de dim 3x3
solve(((B %*% t(B)) + (A %*% t(A)) - 100*I3))


[1] "Matriz A"


[,1]
[1,] 1   
[2,] 2   
[3,] 7

[1] "Dimensión de A:"


[1] 3 1

[1] "Matriz B"


[,1]
[1,] 3   
[2,] 4   
[3,] 8

[1] "Dimensión de B:"


[1] 3 1

[,1]
[1,] 67

[,1] [,2] [,3]
[1,] 67   134  469

[,1]         [,2]         [,3]       
[1,] -0.007923676  0.003123274 0.007843334
[2,]  0.003123274 -0.005350239 0.011483806
[3,]  0.007843334  0.011483806 0.017584735

6) La función diag tiene varios usos, uno de los cuales es tomar un vector como entrada y crea una
matriz cuadrada con ese vector en la diagonal. Crea una matriz 21 × 21 con la secuencia de 10 a 0 y
a 11 (es decir, 11, 10, . . . , 1, 0, 1, . . . , 11).

In [21]:
     matriz <- diag( c(seq(10,0), seq(1,10)), nrow= 21)
     matriz

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 10   0    0    0    0    0    0    0    0    0     ⋯     0     0    
 [2,]  0   9    0    0    0    0    0    0    0    0     ⋯     0     0    
 [3,]  0   0    8    0    0    0    0    0    0    0     ⋯     0     0    
 [4,]  0   0    0    7    0    0    0    0    0    0     ⋯     0     0    
 [5,]  0   0    0    0    6    0    0    0    0    0     ⋯     0     0    
 [6,]  0   0    0    0    0    5    0    0    0    0     ⋯     0     0    
 [7,]  0   0    0    0    0    0    4    0    0    0     ⋯     0     0    
 [8,]  0   0    0    0    0    0    0    3    0    0     ⋯     0     0    
 [9,]  0   0    0    0    0    0    0    0    2    0     ⋯     0     0    
[10,]  0   0    0    0    0    0    0    0    0    1     ⋯     0     0    
[11,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[12,]  0   0    0    0    0    0    0    0    0    0     ⋯     1     0    
[13,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     2    
[14,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[15,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[16,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[17,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[18,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[19,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[20,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
[21,]  0   0    0    0    0    0    0    0    0    0     ⋯     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0      0   
 [2,] 0     0     0     0     0     0     0      0   
 [3,] 0     0     0     0     0     0     0      0   
 [4,] 0     0     0     0     0     0     0      0   
 [5,] 0     0     0     0     0     0     0      0   
 [6,] 0     0     0     0     0     0     0      0   
 [7,] 0     0     0     0     0     0     0      0   
 [8,] 0     0     0     0     0     0     0      0   
 [9,] 0     0     0     0     0     0     0      0   
[10,] 0     0     0     0     0     0     0      0   
[11,] 0     0     0     0     0     0     0      0   
[12,] 0     0     0     0     0     0     0      0   
[13,] 0     0     0     0     0     0     0      0   
[14,] 3     0     0     0     0     0     0      0   
[15,] 0     4     0     0     0     0     0      0   
[16,] 0     0     5     0     0     0     0      0   
[17,] 0     0     0     6     0     0     0      0   
[18,] 0     0     0     0     7     0     0      0   
[19,] 0     0     0     0     0     8     0      0   
[20,] 0     0     0     0     0     0     9      0   
[21,] 0     0     0     0     0     0     0     10

7) Para

<center/> $ A = \begin{bmatrix}
 2 & 0 & 0 & 0 \\ 
 0 & 3 & 0 & 0 \\ 
 0&  0 & 5 &  0\\ 
 0 & 0 & 0 & -1 
\end{bmatrix}$ <center/>  

Comprueba que $A^{-1}\cdot A \, \, - I_{4}$ proporciona una matriz 4 × 4 de ceros.

In [23]:
 A <- diag( c(2,3,5,-1), nrow = 4) # matriz A 
 print("Matriz A")
 A
 I4 <- diag(1, nrow = 4) #matriz identidad de 4x4
 print("Matriz identidad de 4x4")
 I4
 print("Resultado")
 solve(A) %*% A - I4 # comprobación del resultado 


[1] "Matriz A"


[,1] [,2] [,3] [,4]
[1,] 2    0    0     0  
[2,] 0    3    0     0  
[3,] 0    0    5     0  
[4,] 0    0    0    -1

[1] "Matriz identidad de 4x4"


[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

[1] "Resultado"


[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0   
[4,] 0    0    0    0

8) Usa las funciones `matrix()`, `seq()` y `rep()` para construir la matrices de Hankel $5 \times 5$.

In [25]:
    p<- rep (1:5, 5) + rep(0:4,each = 5)
    han <- matrix(p, nrow = 5, byrow = F)
    print("Matriz Hankel 5x5")
    han

[1] "Matriz Hankel 5x5"


[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 2    3    4    5    6   
[3,] 3    4    5    6    7   
[4,] 4    5    6    7    8   
[5,] 5    6    7    8    9

* Convierte el código en una función que puede ser usado para construir matrices de dimensión $n \times n$.

In [34]:
# Ingresamos una cadena de longitud r 
Matrix_Hankel <- function(m) {
  n = (length(m) + 1 ) / 2
  matriz <- matrix(m[rep(seq(1:n),n) + rep(seq(0,n-1), each = n )], nrow= n, byrow = F )
  matriz
}

* Usa esa función para mostrar las salida de Matrices de Hankel de orden $10 \times 10$ y $12 \times 12$.

In [38]:
# Matriz Hankel 5x5 

MH5 <- c(1,2,3,4,5,6,7,8,9)
print("Matriz de Hankel 5x5")
Matrix_Hankel(MH5)

MH10 <- 6:24
print("Matriz de Hankel 10x10")
Matrix_Hankel(MH10)

MH12 <- 34:56
print("Matriz de Hankel 12x12")
Matrix_Hankel(MH12)

[1] "Matriz de Hankel 5x5"


[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 2    3    4    5    6   
[3,] 3    4    5    6    7   
[4,] 4    5    6    7    8   
[5,] 5    6    7    8    9

[1] "Matriz de Hankel 10x10"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  6    7    8    9   10   11   12   13   14   15   
 [2,]  7    8    9   10   11   12   13   14   15   16   
 [3,]  8    9   10   11   12   13   14   15   16   17   
 [4,]  9   10   11   12   13   14   15   16   17   18   
 [5,] 10   11   12   13   14   15   16   17   18   19   
 [6,] 11   12   13   14   15   16   17   18   19   20   
 [7,] 12   13   14   15   16   17   18   19   20   21   
 [8,] 13   14   15   16   17   18   19   20   21   22   
 [9,] 14   15   16   17   18   19   20   21   22   23   
[10,] 15   16   17   18   19   20   21   22   23   24

[1] "Matriz de Hankel 12x12"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
 [1,] 34   35   36   37   38   39   40   41   42   43    44    45   
 [2,] 35   36   37   38   39   40   41   42   43   44    45    46   
 [3,] 36   37   38   39   40   41   42   43   44   45    46    47   
 [4,] 37   38   39   40   41   42   43   44   45   46    47    48   
 [5,] 38   39   40   41   42   43   44   45   46   47    48    49   
 [6,] 39   40   41   42   43   44   45   46   47   48    49    50   
 [7,] 40   41   42   43   44   45   46   47   48   49    50    51   
 [8,] 41   42   43   44   45   46   47   48   49   50    51    52   
 [9,] 42   43   44   45   46   47   48   49   50   51    52    53   
[10,] 43   44   45   46   47   48   49   50   51   52    53    54   
[11,] 44   45   46   47   48   49   50   51   52   53    54    55   
[12,] 45   46   47   48   49   50   51   52   53   54    55    56

9) La matriz de Hilbert $n \times n$ tiene a los elementos $(i,j)$ dados por $1/(i + j-1)$.  

* Escribe una función que muestra una matriz de Hilbert $n \times n$ como salida para entero positivo $n$.

In [43]:
# Matriz Hilbert 
# n es la dimension de la matriz 
  hilbert <- function(n){ 
      i<- 1:n ; 
      1/ outer(i-1,i,"+")  
  }

print("Matriz Hilbert 4x4")
hilbert(4)

[1] "Matriz Hilbert 4x4"


[,1]      [,2]      [,3]      [,4]     
[1,] 1.0000000 0.5000000 0.3333333 0.2500000
[2,] 0.5000000 0.3333333 0.2500000 0.2000000
[3,] 0.3333333 0.2500000 0.2000000 0.1666667
[4,] 0.2500000 0.2000000 0.1666667 0.1428571

 * ¿Son todas las matrices de Hilbert invertibles?  
 
 Sí, ya que al calcular su inversa siempre saldrán valores de tipo entero, aunque a veces se debe redondear. 

* Usa solve() y qr.solve() para calcular la inversa de las matrices Hilbert, por ejemplo, cuando $n = 10$.

In [48]:
print("Usando solve para una matriz de Hilbert de dimensión 10x10")
solve(hilbert(10))

print("Usando qr.solve para una matriz de Hilbert de dimensión 10x10")
qr.solve(hilbert(10), tol = 0)

[1] "Usando solve para una matriz de Hilbert de dimensión 10x10"


[,1]          [,2]          [,3]          [,4]          [,5]         
 [1,]  9.999719e+01 -4.949757e+03  7.919482e+04 -6.005529e+05       2522295
 [2,] -4.949756e+03  3.266790e+05 -5.880152e+06  4.756344e+07    -208088462
 [3,]  7.919480e+04 -5.880151e+06  1.128980e+08 -9.512635e+08    4280662450
 [4,] -6.005527e+05  4.756343e+07 -9.512634e+08  8.244246e+09  -37871868827
 [5,]  2.522294e+06 -2.080884e+08  4.280662e+09 -3.787187e+10  176734991839
 [6,] -6.305679e+06  5.350810e+08 -1.123668e+10  1.009913e+11 -477183582308
 [7,]  9.608580e+06 -8.323436e+08  1.775667e+10 -1.615857e+11  771204559101
 [8,] -8.750614e+06  7.700557e+08 -1.663323e+10  1.528915e+11 -735791094422
 [9,]  4.375282e+06 -3.898391e+08  8.505604e+09 -7.883452e+10  382044919568
[10,] -9.236661e+05  8.313037e+07 -1.828875e+09  1.706955e+10  -83214282335
      [,6]          [,7]          [,8]          [,9]          [,10]        
 [1,] -6.305682e+06  9.608586e+06 -8.750620e+06  4.375286e+06 -9.236669e+05
 [2,]  5.350812e+08 -8.323439e+08  7.700561e+08 -3.898393e+08  8.313042e+07
 [3,] -1.123669e+10  1.775667e+10 -1.663324e+10  8.505608e+09 -1.828876e+09
 [4,]  1.009913e+11 -1.615857e+11  1.528915e+11 -7.883455e+10  1.706956e+10
 [5,] -4.771836e+11  7.712047e+11 -7.357912e+11  3.820450e+11 -8.321430e+10
 [6,]  1.301409e+12 -2.120813e+12  2.037577e+12 -1.064270e+12  2.330005e+11
 [7,] -2.120813e+12  3.480308e+12 -3.363622e+12  1.765901e+12 -3.883348e+11
 [8,]  2.037577e+12 -3.363622e+12  3.267520e+12 -1.723107e+12  3.804102e+11
 [9,] -1.064270e+12  1.765901e+12 -1.723107e+12  9.122340e+11 -2.020931e+11
[10,]  2.330005e+11 -3.883348e+11  3.804101e+11 -2.020931e+11  4.490964e+10

[1] "Usando qr.solve para una matriz de Hilbert de dimensión 10x10"


[,1]          [,2]          [,3]          [,4]          [,5]         
 [1,]  9.999763e+01 -4.949796e+03  7.919566e+04 -6.005606e+05       2522332
 [2,] -4.949794e+03  3.266822e+05 -5.880222e+06  4.756409e+07    -208091541
 [3,]  7.919557e+04 -5.880218e+06  1.128994e+08 -9.512768e+08    4280726081
 [4,] -6.005595e+05  4.756403e+07 -9.512762e+08  8.244364e+09  -37872432943
 [5,]  2.522326e+06 -2.080912e+08  4.280722e+09 -3.787241e+10  176737626224
 [6,] -6.305764e+06  5.350885e+08 -1.123685e+10  1.009928e+11 -477190694526
 [7,]  9.608718e+06 -8.323557e+08  1.775693e+10 -1.615881e+11  771216047252
 [8,] -8.750745e+06  7.700672e+08 -1.663348e+10  1.528938e+11 -735802046037
 [9,]  4.375350e+06 -3.898451e+08  8.505733e+09 -7.883571e+10  382050600435
[10,] -9.236809e+05  8.313167e+07 -1.828903e+09  1.706981e+10  -83215518397
      [,6]          [,7]          [,8]          [,9]          [,10]        
 [1,] -6.305784e+06  9.608755e+06 -8.750784e+06  4.375372e+06 -9.236858e+05
 [2,]  5.350897e+08 -8.323580e+08  7.700697e+08 -3.898465e+08  8.313200e+07
 [3,] -1.123686e+10  1.775696e+10 -1.663352e+10  8.505756e+09 -1.828909e+09
 [4,]  1.009929e+11 -1.615883e+11  1.528940e+11 -7.883586e+10  1.706985e+10
 [5,] -4.771909e+11  7.712167e+11 -7.358029e+11  3.820511e+11 -8.321566e+10
 [6,]  1.301428e+12 -2.120845e+12  2.037609e+12 -1.064286e+12  2.330042e+11
 [7,] -2.120844e+12  3.480361e+12 -3.363673e+12  1.765928e+12 -3.883407e+11
 [8,]  2.037607e+12 -3.363671e+12  3.267568e+12 -1.723133e+12  3.804158e+11
 [9,] -1.064285e+12  1.765927e+12 -1.723132e+12  9.122472e+11 -2.020961e+11
[10,]  2.330039e+11 -3.883404e+11  3.804156e+11 -2.020960e+11  4.491027e+10

10) 

* Genere un array tridimensional con dimensiones $4 \times 3 \times 2$ que contengan los números del $1$ al $24$.

In [59]:
  miArray <- array(1:24, c(4,3,2))
  print(" Array generado")
  miArray

[1] " Array generado"


, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

* Extraiga la última porción (a[,, 2]) del array y guárdela como una matriz $M$.

In [57]:
  # Extrayendo   
   M <- miArray[,,2]
   print("Matriz M ")
   M
   print("¿Es una matriz?")
   is.matrix(M)

[1] "Matriz M "


[,1] [,2] [,3]
[1,] 13   17   21  
[2,] 14   18   22  
[3,] 15   19   23  
[4,] 16   20   24

[1] "¿Es una matriz?"


[1] TRUE

* Genera un nuevo array de dimensiones $4 \times 3 \times 3$ que es idéntica a la matriz anterior, pero añade la matriz $M$ como la tercera entrada en la tercera dimensión.

In [61]:
arr <- array(c(miArray,M), c(4,3,3))
print("Nuevo array de 4x3x3")
arr 

[1] "Nuevo array de 4x3x3"


, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

, , 3

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

11) Crea una matriz aleatoria entera $6 \times 10$ escogidos entre $1,2,\dots, 10$, ejecutando las siguientes líneas de código.

In [62]:
# Generando la matriz 

  set.seed(75)
  aMat <- matrix(sample(10, size = 60, replace = T), nr = 6)
  print("Matriz aMat")
  aMat

[1] "Matriz aMat"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 3     6   7    7     2    4    3   7     1   4    
[2,] 1     9   8    7     2    6   10   9     5   2    
[3,] 7    10   8    4    10    5    4   8     4   4    
[4,] 4     3   1    1     3    3    9   7     4   2    
[5,] 1     8   1    9     9    8    1   3     7   7    
[6,] 2     6   7    5     6   10    4   6    10   1

(a) Encuentra el número de entradas en cada fila que son mayores que $4$.

In [64]:
print("Cantidad de entradas de filas que son mayores que 4")
apply(aMat,1, function(x) {sum(x>4)})

[1] "Cantidad de entradas de filas que son mayores que 4"


[1] 4 7 6 2 6 7

(b) ¿Qué filas contienen exactamente dos ocurrencias del número siete?

In [66]:
# Averiguamos cuantas veces se repite 7 en una fila 
num_sietes <- apply(aMat,1, function(x) {sum(x==7)})
p <- which(num_sietes == 2) #utilizamos which para saber que indice de fila cumple con dos ocurrencias de siete 
print("Fila(s) con dos ocurrencias del número siete")
p

[1] "Fila(s) con dos ocurrencias del número siete"


[1] 5

(c) Encuentra aquellos pares de columnas cuyo total (sobre ambas columnas) es mayor que 75. La respuesta debería ser una matriz con dos columnas; así, por ejemplo, la fila $(1, 2)$ en la matriz de salida significa que la suma de las columnas $1$ y $2$ en la matriz original es mayor que 75. Se permite repetir una columna; por ejemplo, la matriz de salida final podría contener las filas $(1, 2), (2, 1)$ y $(2, 2)$.

In [67]:
# Esta variable guarda la suma de cada columna 
sum_col <- apply(aMat,2, function(x) { sum(x)})
print("Suma de cada columna")
sum_col

#Ahora guardaremos todas las sumas posibles entre columnas en una matriz 
col_matrix <- matrix(sum_col + rep(sum_col, each = 10), nrow = 10, byrow =  F)
print("Matriz donde cada valor sea (i,j) contiene la suma de la i-ésima y j-ésima columna")       
col_matrix
      
#Luego aplicamos la funcion which, el cual nos devolverá los índices que cumplen con la condición en el argumento
matrix_resul <- which(col_matrix>75, arr.ind = TRUE)
print("Matriz de pares de columnas donde su suma es mayor que 75")
matrix_resul

[1] "Suma de cada columna"


[1] 18 42 32 33 32 36 31 40 31 20

[1] "Matriz donde cada valor sea (i,j) contiene la suma de la i-ésima y j-ésima columna"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] 36   60   50   51   50   54   49   58   49   38   
 [2,] 60   84   74   75   74   78   73   82   73   62   
 [3,] 50   74   64   65   64   68   63   72   63   52   
 [4,] 51   75   65   66   65   69   64   73   64   53   
 [5,] 50   74   64   65   64   68   63   72   63   52   
 [6,] 54   78   68   69   68   72   67   76   67   56   
 [7,] 49   73   63   64   63   67   62   71   62   51   
 [8,] 58   82   72   73   72   76   71   80   71   60   
 [9,] 49   73   63   64   63   67   62   71   62   51   
[10,] 38   62   52   53   52   56   51   60   51   40

[1] "Matriz de pares de columnas donde su suma es mayor que 75"


row col
[1,] 2   2  
[2,] 6   2  
[3,] 8   2  
[4,] 2   6  
[5,] 8   6  
[6,] 2   8  
[7,] 6   8  
[8,] 8   8

¿Qué sucede si no se permiten repeticiones? Entonces, sólo se permitiría $(1, 2)$ de $(1, 2), (2, 1)$ y $(2, 2)$?

In [68]:
#Colocamos a los valores que son (j,i) de (i,j) ya que no los contamos para el cálculo 
col_matrix[lower.tri(col_matrix, diag = TRUE)] <- NA
print("Matriz solo con los valores que son de la forma (i,j)")
col_matrix

#Ahora hacemos el mismo procedimiento que en el caso anterior 
matrix_resul_1<- which(col_matrix>75, arr.ind = TRUE)  
print("Matriz con índices que cumplen que la suma es mayor a 75")
matrix_resul_1

[1] "Matriz solo con los valores que son de la forma (i,j)"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,] NA   60   50   51   50   54   49   58   49   38   
 [2,] NA   NA   74   75   74   78   73   82   73   62   
 [3,] NA   NA   NA   65   64   68   63   72   63   52   
 [4,] NA   NA   NA   NA   65   69   64   73   64   53   
 [5,] NA   NA   NA   NA   NA   68   63   72   63   52   
 [6,] NA   NA   NA   NA   NA   NA   67   76   67   56   
 [7,] NA   NA   NA   NA   NA   NA   NA   71   62   51   
 [8,] NA   NA   NA   NA   NA   NA   NA   NA   71   60   
 [9,] NA   NA   NA   NA   NA   NA   NA   NA   NA   51   
[10,] NA   NA   NA   NA   NA   NA   NA   NA   NA   NA

[1] "Matriz con índices que cumplen que la suma es mayor a 75"


row col
[1,] 2   6  
[2,] 2   8  
[3,] 6   8